---
title: "Step F PSY4960"
output: pdf_document
fig_width: 7
fig_height: 6
fig_caption: true
---
Libraries and Code for Indices 
```{r}
library(ggplot2)
library(readr)
friendDat <- read_csv("C:/Users/katem/Downloads/final spreadsheet - no missing data 48 participants.csv")
```

```{r}
#INDICE FOR WHETHER THE FRIEND CHARACTER WAS CHOSEN OR NOT 
chooseNumeric1 <- ifelse(friendDat$choose_friend1=="f", 1, 0)
chooseNumeric2 <- ifelse(friendDat$choose_friend2=="f", 1, 0)
chooseNumeric3 <- ifelse(friendDat$choose_friend3=="f", 1, 0)
chooseNumeric4 <- ifelse(friendDat$choose_friend4=="f", 1, 0)
chooseNumeric5 <- ifelse(friendDat$choose_friend5=="f", 1, 0)
chooseNumeric6 <- ifelse(friendDat$choose_friend6=="f", 1, 0)

choose_friend_indice <- c(chooseNumeric1 + chooseNumeric2 + chooseNumeric3 +chooseNumeric4 + chooseNumeric5 +chooseNumeric6)
```

```{r}
#INDICE FOR COMFORTING BEHAVIORS 
comfort1 <- ifelse(friendDat$type_help1=="comfort", 1, 0)
comfort2 <- ifelse(friendDat$type_help2=="comfort", 1, 0)
comfort3 <- ifelse(friendDat$type_help3=="comfort", 1, 0)
comfort4 <- ifelse(friendDat$type_help4=="comfort", 1, 0)
comfort5 <- ifelse(friendDat$type_help5=="comfort", 1, 0)
comfort6 <- ifelse(friendDat$type_help6=="comfort", 1, 0)

comfort_indice <- c(comfort1+comfort2+comfort3+comfort4+comfort5+comfort6)
```

```{r}
#INDICE FOR SHARING BEHAVIORS 
share1 <- ifelse(friendDat$type_help1=="share", 1, 0)
share2 <- ifelse(friendDat$type_help2=="share", 1, 0)
share3 <- ifelse(friendDat$type_help3=="share", 1, 0)
share4 <- ifelse(friendDat$type_help4=="share", 1, 0)
share5 <- ifelse(friendDat$type_help5=="share", 1, 0)
share6 <- ifelse(friendDat$type_help6=="share", 1, 0)

share_indice <- c(share1+share2+share3+share4+share5+share6)
```

```{r}
#INDICE FOR INSTRUMENTAL HELPING BEHAVIORS 
goal1 <- ifelse(friendDat$type_help1=="goal", 1, 0)
goal2 <- ifelse(friendDat$type_help2=="goal", 1, 0)
goal3 <- ifelse(friendDat$type_help3=="goal", 1, 0)
goal4 <- ifelse(friendDat$type_help4=="goal", 1, 0)
goal5 <- ifelse(friendDat$type_help5=="goal", 1, 0)
goal6 <- ifelse(friendDat$type_help6=="goal", 1, 0)

goal_indice <- c(goal1+goal2+goal3+goal4+goal5+goal6)
```

```{r}
#INDICE FOR SPECIFICITY  
Specific1 <- ifelse(friendDat$`specific 1`=="not", 0, 1)
Specific2 <- ifelse(friendDat$`specific 2`=="not", 0, 1)
Specific3 <- ifelse(friendDat$`specific 3`=="not", 0, 1)
Specific4 <- ifelse(friendDat$`specific 4`=="not", 0, 1)
Specific5 <- ifelse(friendDat$`specific 5`=="not", 0, 1)
Specific6 <- ifelse(friendDat$`specific 6`=="not", 0, 1)

specific_indice <- c(Specific1+Specific2+Specific3+Specific4+Specific5+Specific6)
```

```{r}
age <- friendDat$age
sex <- friendDat$sex
sex <- car::recode(sex, '
"f" = "Female";
"m"="Male"
  ')

friendDatI <- cbind.data.frame(sex,age, choose_friend_indice, comfort_indice, share_indice, goal_indice, specific_indice)
```

```{r}
#Dataset for H0(1)
chooseFriendTotal <- c(friendDat$choose_friend1, friendDat$choose_friend2,friendDat$choose_friend3, friendDat$choose_friend4,friendDat$choose_friend5, friendDat$choose_friend6)
chooseFriendTotal <- car::recode(chooseFriendTotal, '
"f" = "Friend Character";
"n"="Nonfriend Character"')
typeHelpTotal <- c(friendDat$type_help1, friendDat$type_help2, friendDat$type_help3, friendDat$type_help4, friendDat$type_help5, friendDat$type_help6)
typeHelpTotal <- car::recode(typeHelpTotal, '
"goal" = "Instrumental";
"comfort"="Comforting";
"share"="Sharing" ;
"none"="Other" ')
smallFriend <- cbind.data.frame(chooseFriendTotal, typeHelpTotal)
smallFriendTable <- table(smallFriend)
```



Hypothesis 1
```{r}
#H01: Children will display different helping behaviors when responding to a friend's needs than a nonfriends needs. 

#Note: I chose to use a chi-square test of independence for this hypothesis because my research question is about whether the type of helping behavior is independent of whether the friend or nonfriend character is helping. I made indices but am not using them for this specific analysis because I want to look at these variables categorically. I do not think the number of times a child chose the friend character or engaged in a specific helping behavior(sharing, helping, instrumental) is relevant to this research question. 

chisq.test(smallFriendTable, correct=FALSE)

ggplot(smallFriend, aes(x=typeHelpTotal, fill=chooseFriendTotal))+geom_bar(position = position_dodge())+theme_classic()+
  scale_fill_manual(values=c("#ECB7B3","#8E929B"), name="Choice of Helper")+ggtitle("Type of Helping Behavior and Choice of Helper")+ylab("Count")+xlab("Type of Help Provided")
```



Hypothesis 2 
```{r}
#H02: Older children will display different helping behaviors than younger children.

#Note: Because this hypothesis is broad, I decided to break it down into 3 analyses by separating the three types of prosocial helping behaviors (sharing, comforting, and instrumental helping). I looked at the effect of age on the number of sharing, comforting, and instrumental helping behaviors that occurred throughout all six trials. Analysis 1 focuses on sharing behaviors, analysis 2 focuses on comforting behaviors, and analysis 3 focuses on isntrumental helping.  

#A1: Age differences in sharing behaviors 
summary ( aov(share_indice~age, data=friendDatI) )
ggplot(friendDatI, aes(share_indice, fill= as.factor(age)))+geom_bar(position = position_dodge())+scale_x_continuous(n.breaks=7) + expand_limits(x=c(0,6))+ggtitle("Frequency of Sharing Behaviors By Age Group")+xlab("Number of Trials in Which Sharing Behavior Occurred")+ylab("Count")+theme_classic()+
  scale_fill_manual(values=c("#ECB7B3","#8E929B","#A4B8AC"), name="Age")


#A2: Age differences in comforting behaviors 
summary ( aov(comfort_indice~age, data=friendDatI) )
ggplot(friendDatI, aes(comfort_indice, fill= as.factor(age)))+geom_bar(position = position_dodge())+scale_x_continuous(n.breaks=7) + expand_limits(x=c(0,6))+ggtitle("Frequency of Comforting Behaviors By Age Group")+xlab("Number of Trials in Which Comforting Behavior Occurred")+ylab("Count")+theme_classic()+
  scale_fill_manual(values=c("#ECB7B3","#8E929B","#A4B8AC"), name="Age")


#A3: Age differences in instrumental helping behaviors
summary ( aov(goal_indice~age, data=friendDatI) )
ggplot(friendDatI, aes(goal_indice, fill= as.factor(age)))+geom_bar(position = position_dodge())+scale_x_continuous(n.breaks=7) + expand_limits(x=c(0,6))+ggtitle("Frequency of Instrumental Helping Behaviors By Age Group")+xlab("Number of Trials in Which Instrumental Helping Occurred")+ylab("Count")+theme_classic()+
  scale_fill_manual(values=c("#ECB7B3","#8E929B","#A4B8AC"), name="Age")
```



Hypothesis 3
```{r}
#H03: Female children will display more comforting behaviors than male children.

t.test(friendDatI$comfort_indice~friendDatI$sex, var.equal=TRUE)

ggplot(friendDatI, aes(comfort_indice, fill= as.factor(sex) ))+geom_bar(position = position_dodge())+theme_classic()+
  scale_fill_manual(values=c("#ECB7B3","#8E929B"), name="Gender")+ggtitle("Frequency of Comforting Behavior By Gender")+ylab("Count")+xlab("Number of Trials in Which Comforting Behaviors Occurred")+scale_x_continuous(n.breaks=7) + expand_limits(x=c(0,6))
```



Hypothesis 4
```{r}
#H04: Older children will tell more specific stories compared to younger children. 

summary ( aov(specific_indice~age, data=friendDatI) )

ggplot(friendDatI, aes(specific_indice, fill= as.factor(age) ))+geom_bar(position = position_dodge())+theme_classic()+
  scale_fill_manual(values=c("#ECB7B3","#8E929B","#A4B8AC"), name="Age")+ggtitle("Frequency of Specific Storytelling By Age")+ expand_limits(x=c(0,2.5))+scale_x_continuous(n.breaks=3)+ylab("Count")+xlab("Number of Specific Stories Told")
```



Hypothesis 5
```{r}
#H05: Older children will pick the friend character to help more often than the younger children. 

summary(aov(choose_friend_indice~age, data=friendDatI)) 

ggplot(friendDatI, aes(choose_friend_indice, fill= as.factor(age) ))+geom_bar(position = position_dodge())+theme_classic()+
  scale_fill_manual(values=c("#ECB7B3","#8E929B","#A4B8AC"), name="Age")+ expand_limits(x=c(0,6))+scale_x_continuous(n.breaks=7)+ylab("Count")+xlab("Number of Trials the Friend Was the Helper")+theme(panel.background = element_blank(),
  axis.line=element_line(color="black"),
  axis.title=element_text(size=18, color="black", face="bold"), axis.text.y = element_text(size=17, color="black"), axis.text.x = element_text(size=17, color="black"), legend.background = element_rect(color="black"), legend.text = element_text(size=15))
```

Mean and standard deviation of the number of trials each age group chose the friend character as the helper
```{r}
library(tidyverse)
four <- subset(friendDatI, friendDatI$age=="4")

five <- subset(friendDatI, friendDatI$age=="5")

six <- subset(friendDatI, friendDatI$age=="6")
```

```{r}
mean(four$choose_friend_indice)
sd(four$choose_friend_indice)
```
```{r}
mean(five$choose_friend_indice)
sd(five$choose_friend_indice)
```
```{r}
mean(six$choose_friend_indice)
sd(six$choose_friend_indice)
```




